# Get-FluxAlias.ps1
# Resolves an alias to a PackageId.
# Checks flux-aliases.csv first (if present), then falls back to built-in list.

function Get-FluxAlias {
    param(
        [Parameter(Mandatory, Position = 0)]
        [string]$Query
    )

    # ── Check CSV first (user customizations take priority) ───────────────────
    $aliasFile = Join-Path $PSScriptRoot "flux-aliases.csv"
    if (Test-Path $aliasFile) {
        $csvAliases = Import-Csv $aliasFile | Where-Object { $_.Alias -notmatch "^#" -and $_.Alias -ne "" }
        $csvMatch   = $csvAliases | Where-Object { $_.Alias -ieq $Query } | Select-Object -First 1
        if ($csvMatch) { return $csvMatch.PackageId }
    }

    # ── Built-in alias table (fallback) ───────────────────────────────────────
    $builtIn = @{
        # Browsers
        "chrome"              = "Google.Chrome"
        "firefox"             = "Mozilla.Firefox"
        "edge"                = "Microsoft.Edge"
        "brave"               = "Brave.Brave"
        "opera"               = "Opera.Opera"
        "operagx"             = "Opera.OperaGX"
        "vivaldi"             = "VivaldiTechnologies.Vivaldi"
        "waterfox"            = "Waterfox.Waterfox"
        "librewolf"           = "LibreWolf.LibreWolf"
        "tor"                 = "TorProject.TorBrowser"
        "chromium"            = "Hibbiki.Chromium"
        # Code Editors & IDEs
        "vscode"              = "Microsoft.VisualStudioCode"
        "vscodium"            = "VSCodium.VSCodium"
        "notepad++"           = "Notepad++.Notepad++"
        "notepadplusplus"     = "Notepad++.Notepad++"
        "sublime"             = "SublimeHQ.SublimeText.4"
        "vim"                 = "vim.vim"
        "neovim"              = "Neovim.Neovim"
        "emacs"               = "GNU.Emacs"
        "nano"                = "GNU.Nano"
        "intellij"            = "JetBrains.IntelliJIDEA.Community"
        "pycharm"             = "JetBrains.PyCharm.Community"
        "webstorm"            = "JetBrains.WebStorm"
        "phpstorm"            = "JetBrains.PhpStorm"
        "rider"               = "JetBrains.Rider"
        "clion"               = "JetBrains.CLion"
        "goland"              = "JetBrains.GoLand"
        "datagrip"            = "JetBrains.DataGrip"
        "androidstudio"       = "Google.AndroidStudio"
        "visualstudio"        = "Microsoft.VisualStudio.2022.Community"
        "codeblocks"          = "CodeBlocks.CodeBlocks"
        # Version Control
        "git"                 = "Git.Git"
        "github-desktop"      = "GitHub.GitHubDesktop"
        "gitkraken"           = "Axosoft.GitKraken"
        "sourcetree"          = "Atlassian.Sourcetree"
        "tortoisegit"         = "TortoiseGit.TortoiseGit"
        "fork"                = "Fork.Fork"
        "lazygit"             = "JesseDuffield.lazygit"
        # Terminals & Shells
        "windowsterminal"     = "Microsoft.WindowsTerminal"
        "wt"                  = "Microsoft.WindowsTerminal"
        "powershell"          = "Microsoft.PowerShell"
        "pwsh"                = "Microsoft.PowerShell"
        "cmder"               = "cmder-dev.cmder"
        "conemu"              = "Maximus5.ConEmu"
        "wezterm"             = "wez.wezterm"
        "alacritty"           = "Alacritty.Alacritty"
        "hyper"               = "Vercel.Hyper"
        "tabby"               = "Eugeny.Tabby"
        "putty"               = "PuTTY.PuTTY"
        # SSH & Remote
        "winscp"              = "WinSCP.WinSCP"
        "filezilla"           = "TimKosse.FileZilla.Client"
        "cyberduck"           = "iterate.cyberduck"
        "mremoteng"           = "mRemoteNG.mRemoteNG"
        "mobaxterm"           = "Mobatek.MobaXterm"
        "anydesk"             = "AnyDeskSoftwareGmbH.AnyDesk"
        "teamviewer"          = "TeamViewer.TeamViewer"
        "rustdesk"            = "RustDesk.RustDesk"
        "parsec"              = "Parsec.Parsec"
        "screenconnect"       = "ConnectWise.ScreenConnect"
        "splashtop"           = "Splashtop.SplashtopBusiness"
        # Networking
        "wireshark"           = "WiresharkFoundation.Wireshark"
        "nmap"                = "Insecure.Nmap"
        "openvpn"             = "OpenVPNTechnologies.OpenVPN"
        "wireguard"           = "WireGuard.WireGuard"
        "tailscale"           = "Tailscale.Tailscale"
        "zerotier"            = "ZeroTier.ZeroTierOne"
        "advanced-ipscanner"  = "Famatech.AdvancedIPScanner"
        "fiddler"             = "Telerik.Fiddler.Classic"
        # API Tools
        "postman"             = "Postman.Postman"
        "insomnia"            = "Insomnia.Insomnia"
        "bruno"               = "Bruno.Bruno"
        # Databases
        "dbeaver"             = "dbeaver.dbeaver"
        "mysql-workbench"     = "Oracle.MySQLWorkbench"
        "pgadmin"             = "PostgreSQL.pgAdmin"
        "ssms"                = "Microsoft.SQLServerManagementStudio"
        "tableplus"           = "TablePlus.TablePlus"
        "redis-insight"       = "RedisLabs.RedisInsight"
        "mongodb-compass"     = "MongoDB.Compass.Full"
        # Languages & Runtimes
        "python"              = "Python.Python.3.12"
        "python311"           = "Python.Python.3.11"
        "python310"           = "Python.Python.3.10"
        "node"                = "OpenJS.NodeJS"
        "nodejs"              = "OpenJS.NodeJS"
        "node-lts"            = "OpenJS.NodeJS.LTS"
        "nvm"                 = "CoreyButler.NVMforWindows"
        "bun"                 = "Oven-sh.Bun"
        "deno"                = "DenoLand.Deno"
        "ruby"                = "RubyInstallerTeam.Ruby.3.2"
        "java"                = "Oracle.JDK.21"
        "java17"              = "Oracle.JDK.17"
        "openjdk"             = "EclipseAdoptium.Temurin.21.JDK"
        "golang"              = "GoLang.Go"
        "go"                  = "GoLang.Go"
        "rust"                = "Rustlang.Rustup"
        "dotnet"              = "Microsoft.DotNet.Runtime.8"
        "dotnet-sdk"          = "Microsoft.DotNet.SDK.8"
        "php"                 = "PHP.PHP.8.3"
        "perl"                = "StrawberryPerl.StrawberryPerl"
        "r"                   = "RProject.R"
        "julia"               = "Julialang.Julia"
        # Build Tools
        "cmake"               = "Kitware.CMake"
        "ninja"               = "Ninja-build.Ninja"
        "gradle"              = "Gradle.Gradle"
        "maven"               = "Apache.Maven"
        "llvm"                = "LLVM.LLVM"
        "mingw"               = "MinGW.MinGW"
        "msys2"               = "MSYS2.MSYS2"
        # Cloud & DevOps
        "docker"              = "Docker.DockerDesktop"
        "podman"              = "RedHat.Podman"
        "kubectl"             = "Kubernetes.kubectl"
        "helm"                = "Helm.Helm"
        "minikube"            = "Kubernetes.minikube"
        "terraform"           = "Hashicorp.Terraform"
        "vagrant"             = "Hashicorp.Vagrant"
        "awscli"              = "Amazon.AWSCLI"
        "aws"                 = "Amazon.AWSCLI"
        "azure-cli"           = "Microsoft.AzureCLI"
        "az"                  = "Microsoft.AzureCLI"
        "gcloud"              = "Google.CloudSDK"
        "pulumi"              = "Pulumi.Pulumi"
        # Virtualization
        "virtualbox"          = "Oracle.VirtualBox"
        "vmware"              = "VMware.WorkstationPro"
        "vmware-player"       = "VMware.WorkstationPlayer"
        # Communication
        "discord"             = "Discord.Discord"
        "slack"               = "SlackTechnologies.Slack"
        "teams"               = "Microsoft.Teams"
        "zoom"                = "Zoom.Zoom"
        "skype"               = "Microsoft.Skype"
        "telegram"            = "Telegram.TelegramDesktop"
        "signal"              = "OpenWhisperSystems.Signal"
        "whatsapp"            = "WhatsApp.WhatsApp"
        "webex"               = "Cisco.WebexTeams"
        # Productivity & Office
        "libreoffice"         = "TheDocumentFoundation.LibreOffice"
        "onlyoffice"          = "ONLYOFFICE.DesktopEditors"
        "wpsoffice"           = "Kingsoft.WPSOffice"
        "notion"              = "Notion.Notion"
        "obsidian"            = "Obsidian.Obsidian"
        "logseq"              = "Logseq.Logseq"
        "onenote"             = "Microsoft.OneNote"
        "todoist"             = "Doist.Todoist"
        "ticktick"            = "Appest.TickTick"
        # Password Managers
        "bitwarden"           = "Bitwarden.Bitwarden"
        "keepass"             = "DominikReichl.KeePass"
        "keepassxc"           = "KeePassXCTeam.KeePassXC"
        "1password"           = "AgileBits.1Password"
        "dashlane"            = "Dashlane.Dashlane"
        "nordpass"            = "NordSecurity.NordPass"
        # Security
        "malwarebytes"        = "Malwarebytes.Malwarebytes"
        "avast"               = "AVAST.Avast"
        "bitdefender"         = "Bitdefender.Bitdefender"
        "veracrypt"           = "IDRIX.VeraCrypt"
        "cryptomator"         = "Cryptomator.Cryptomator"
        "gpg"                 = "GnuPG.GnuPG"
        "kleopatra"           = "KDE.Kleopatra"
        # File Management
        "7zip"                = "7zip.7zip"
        "winrar"              = "RARLab.WinRAR"
        "peazip"              = "GiorgioTani.PeaZip"
        "bandizip"            = "Bandisoft.Bandizip"
        "nanazip"             = "M2Team.NanaZip"
        "everything"          = "voidtools.Everything"
        "totalcommander"      = "Ghisler.TotalCommander"
        "freecommander"       = "FreeCommander.FreeCommander"
        "spacesniffer"        = "UderzoSoftware.SpaceSniffer"
        "treesize"            = "JAMSoftware.TreeSize.Free"
        "wiztree"             = "AntibodySoftware.WizTree"
        "dupeguru"            = "DupeGuru.DupeGuru"
        "teracopy"            = "CodeSector.TeraCopy"
        # System Tools
        "powertoys"           = "Microsoft.PowerToys"
        "autoruns"            = "Microsoft.Sysinternals.Autoruns"
        "procexp"             = "Microsoft.Sysinternals.ProcessExplorer"
        "procmon"             = "Microsoft.Sysinternals.ProcessMonitor"
        "tcpview"             = "Microsoft.Sysinternals.TCPView"
        "cpu-z"               = "CPUID.CPU-Z"
        "gpu-z"               = "TechPowerUp.GPU-Z"
        "hwinfo"              = "REALiX.HWiNFO"
        "hwmonitor"           = "CPUID.HWMonitor"
        "msi-afterburner"     = "Guru3D.MSIAfterburner"
        "speccy"              = "Piriform.Speccy"
        "crystaldiskinfo"     = "CrystalDewWorld.CrystalDiskInfo"
        "crystaldiskmark"     = "CrystalDewWorld.CrystalDiskMark"
        # Cleanup
        "ccleaner"            = "Piriform.CCleaner"
        "bleachbit"           = "BleachBit.BleachBit"
        "revo-uninstaller"    = "RevoUninstaller.RevoUninstaller"
        "bulk-crap-uninstaller" = "Klocman.BulkCrapUninstaller"
        # Backup & Sync
        "freefilesync"        = "FreeFileSync.FreeFileSync"
        "duplicati"           = "Duplicati.Duplicati"
        "restic"              = "Restic.Restic"
        "macrium"             = "Macrium.Reflect.Free"
        "veeam"               = "Veeam.AgentforWindows"
        # Cloud Storage
        "dropbox"             = "Dropbox.Dropbox"
        "googledrive"         = "Google.GoogleDrive"
        "onedrive"            = "Microsoft.OneDrive"
        "mega"                = "Mega.MEGASync"
        "nextcloud"           = "Nextcloud.NextcloudDesktop"
        "syncthing"           = "Syncthing.Syncthing"
        # Media Players
        "vlc"                 = "VideoLAN.VLC"
        "mpv"                 = "mpv.mpv"
        "mpc-hc"              = "clsid2.mpc-hc"
        "potplayer"           = "Daum.PotPlayer"
        "foobar2000"          = "PeterPavlovic.foobar2000"
        "aimp"                = "AIMP.AIMP"
        "musicbee"            = "MusicBee.MusicBee"
        # Streaming & Recording
        "obs"                 = "OBSProject.OBSStudio"
        "kdenlive"            = "KDE.Kdenlive"
        "davinci"             = "BlackmagicDesign.DaVinciResolve"
        "handbrake"           = "HandBrake.HandBrake"
        "ffmpeg"              = "Gyan.FFmpeg"
        "audacity"            = "Audacity.Audacity"
        # Image Editing
        "gimp"                = "GIMP.GIMP"
        "inkscape"            = "Inkscape.Inkscape"
        "krita"               = "KDE.Krita"
        "irfanview"           = "IrfanSkiljan.IrfanView"
        "paint.net"           = "dotPDN.PaintDotNet"
        "darktable"           = "darktable.darktable"
        "imagemagick"         = "ImageMagick.ImageMagick"
        # Screenshots
        "greenshot"           = "Greenshot.Greenshot"
        "sharex"              = "ShareX.ShareX"
        "flameshot"           = "Flameshot.Flameshot"
        "snagit"              = "TechSmith.SnagIt"
        # PDF
        "sumatra"             = "SumatraPDF.SumatraPDF"
        "acrobat-reader"      = "Adobe.Acrobat.Reader.64-bit"
        "adobe-reader"        = "Adobe.Acrobat.Reader.64-bit"
        "foxitreader"         = "Foxit.FoxitReader"
        "pdf24"               = "PDF24.PDF24Creator"
        "pdfsam"              = "PDFsam.PDFsam"
        "okular"              = "KDE.Okular"
        # Design
        "figma"               = "Figma.Figma"
        "blender"             = "BlenderFoundation.Blender"
        "freecad"             = "FreeCAD.FreeCAD"
        # Gaming
        "steam"               = "Valve.Steam"
        "epicgames"           = "EpicGames.EpicGamesLauncher"
        "gog"                 = "GOGcom.GalaxyClient"
        "battlenet"           = "Blizzard.BattleNet"
        "ubisoft"             = "Ubisoft.Connect"
        "playnite"            = "Playnite.Playnite"
        # Utilities
        "rufus"               = "Rufus.Rufus"
        "etcher"              = "Balena.Etcher"
        "ventoy"              = "Ventoy.Ventoy"
        "ditto"               = "Ditto.Ditto"
        "winmerge"            = "WinMerge.WinMerge"
        "autohotkey"          = "AutoHotkey.AutoHotkey"
        "flow-launcher"       = "Flow-Launcher.Flow-Launcher"
        # CLI Tools
        "curl"                = "cURL.cURL"
        "wget"                = "GnuWin32.Wget"
        "jq"                  = "jqlang.jq"
        "fd"                  = "sharkdp.fd"
        "bat"                 = "sharkdp.bat"
        "ripgrep"             = "BurntSushi.ripgrep"
        "rg"                  = "BurntSushi.ripgrep"
        "fzf"                 = "junegunn.fzf"
        "starship"            = "Starship.Starship"
        "oh-my-posh"          = "JanDeDobbeleer.OhMyPosh"
        "zoxide"              = "ajeetdsouza.zoxide"
        "neofetch"            = "nepnep.neofetch"
        "fastfetch"           = "Fastfetch-cli.Fastfetch"
        # Download Managers
        "jdownloader"         = "AppWork.JDownloader"
        "freedownloadmanager" = "FreeDownloadManager.FDM"
        "aria2"               = "aria2.aria2"
        # Email
        "thunderbird"         = "Mozilla.Thunderbird"
        "outlook"             = "Microsoft.OutlookForWindows"
        "mailbird"            = "Mailbird.Mailbird"
        # Fonts
        "cascadia-code"       = "Microsoft.CascadiaCode"
        "firacode"            = "tonsky.FiraCode"
        "jetbrains-mono"      = "JetBrains.Mono"
        # Monitoring / RMM
        "pulseway"            = "Pulseway.Pulseway"
        "ninja-rmm"           = "NinjaRMM.NinjaRMMAgent"
        "huntress"            = "HuntressLabs.HuntressAgent"
        "zabbix-agent"        = "Zabbix.ZabbixAgent"
        "datadog"             = "Datadog.Agent"
        # Notes & Writing
        "typora"              = "Typora.Typora"
        "marktext"            = "MarkText.MarkText"
        "joplin"              = "Joplin.Joplin"
        "standardnotes"       = "StandardNotes.StandardNotes"
        "simplenote"          = "Automattic.Simplenote"
        # Benchmark
        "cinebench"           = "Maxon.CinebenchR23"
        "geekbench"           = "PrimatelLabs.Geekbench"
        "passmark"            = "Passmark.PerformanceTest"
        # Web Dev
        "xampp"               = "ApacheFriends.XAMPP"
        "laragon"             = "leokhoa.Laragon"
        "nginx"               = "Nginx.Nginx"
        "caddy"               = "CaddyServer.Caddy"
        # Translation
        "deepl"               = "DeepL.DeepL"
    }

    $key = $Query.ToLower()
    if ($builtIn.ContainsKey($key)) {
        return $builtIn[$key]
    }

    return $null
}
